//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaHKS.GenelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IllerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class IllerIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorModel", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Core.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class ErrorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IllerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class IllerCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.IlDTO> IllerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.IlDTO> Iller {
            get {
                return this.IllerField;
            }
            set {
                if ((object.ReferenceEquals(this.IllerField, value) != true)) {
                    this.IllerField = value;
                    this.RaisePropertyChanged("Iller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class IlDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IlAdi {
            get {
                return this.IlAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.IlAdiField, value) != true)) {
                    this.IlAdiField = value;
                    this.RaisePropertyChanged("IlAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlcelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class IlcelerIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlId {
            get {
                return this.IlIdField;
            }
            set {
                if ((this.IlIdField.Equals(value) != true)) {
                    this.IlIdField = value;
                    this.RaisePropertyChanged("IlId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlcelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class IlcelerCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.IlceDTO> IlcelerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.IlceDTO> Ilceler {
            get {
                return this.IlcelerField;
            }
            set {
                if ((object.ReferenceEquals(this.IlcelerField, value) != true)) {
                    this.IlcelerField = value;
                    this.RaisePropertyChanged("Ilceler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IlceDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class IlceDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IlceAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IlceAdi {
            get {
                return this.IlceAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.IlceAdiField, value) != true)) {
                    this.IlceAdiField = value;
                    this.RaisePropertyChanged("IlceAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class BeldelerIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceId {
            get {
                return this.IlceIdField;
            }
            set {
                if ((this.IlceIdField.Equals(value) != true)) {
                    this.IlceIdField = value;
                    this.RaisePropertyChanged("IlceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class BeldelerCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.BeldeDTO> BeldelerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.BeldeDTO> Beldeler {
            get {
                return this.BeldelerField;
            }
            set {
                if ((object.ReferenceEquals(this.BeldelerField, value) != true)) {
                    this.BeldelerField = value;
                    this.RaisePropertyChanged("Beldeler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BeldeDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class BeldeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeldeAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeldeAdi {
            get {
                return this.BeldeAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BeldeAdiField, value) != true)) {
                    this.BeldeAdiField = value;
                    this.RaisePropertyChanged("BeldeAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UlkelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UlkelerIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UlkelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class UlkelerCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.UlkeDTO> UlkelerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.UlkeDTO> Ulkeler {
            get {
                return this.UlkelerField;
            }
            set {
                if ((object.ReferenceEquals(this.UlkelerField, value) != true)) {
                    this.UlkelerField = value;
                    this.RaisePropertyChanged("Ulkeler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UlkeDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class UlkeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UlkeAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UlkeAdi {
            get {
                return this.UlkeAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.UlkeAdiField, value) != true)) {
                    this.UlkeAdiField = value;
                    this.RaisePropertyChanged("UlkeAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HalIciIsyeriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class HalIciIsyeriIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikVergiNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo {
            get {
                return this.TcKimlikVergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikVergiNoField, value) != true)) {
                    this.TcKimlikVergiNoField = value;
                    this.RaisePropertyChanged("TcKimlikVergiNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HalIciIsyeriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class HalIciIsyeriCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.HalIciIsyeriDTO> IsyerleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.HalIciIsyeriDTO> Isyerleri {
            get {
                return this.IsyerleriField;
            }
            set {
                if ((object.ReferenceEquals(this.IsyerleriField, value) != true)) {
                    this.IsyerleriField = value;
                    this.RaisePropertyChanged("Isyerleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HalIciIsyeriDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class HalIciIsyeriDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HalAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsyeriAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikVergiNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HalAdi {
            get {
                return this.HalAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.HalAdiField, value) != true)) {
                    this.HalAdiField = value;
                    this.RaisePropertyChanged("HalAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HalId {
            get {
                return this.HalIdField;
            }
            set {
                if ((this.HalIdField.Equals(value) != true)) {
                    this.HalIdField = value;
                    this.RaisePropertyChanged("HalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsyeriAdi {
            get {
                return this.IsyeriAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.IsyeriAdiField, value) != true)) {
                    this.IsyeriAdiField = value;
                    this.RaisePropertyChanged("IsyeriAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo {
            get {
                return this.TcKimlikVergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikVergiNoField, value) != true)) {
                    this.TcKimlikVergiNoField = value;
                    this.RaisePropertyChanged("TcKimlikVergiNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsletmeTurleriIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class IsletmeTurleriIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsletmeTurleriCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class IsletmeTurleriCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.IsletmeTuruDTO> IsletmeTurleriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.IsletmeTuruDTO> IsletmeTurleri {
            get {
                return this.IsletmeTurleriField;
            }
            set {
                if ((object.ReferenceEquals(this.IsletmeTurleriField, value) != true)) {
                    this.IsletmeTurleriField = value;
                    this.RaisePropertyChanged("IsletmeTurleri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsletmeTuruDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class IsletmeTuruDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsletmeTuruAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsletmeTuruAdi {
            get {
                return this.IsletmeTuruAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.IsletmeTuruAdiField, value) != true)) {
                    this.IsletmeTuruAdiField = value;
                    this.RaisePropertyChanged("IsletmeTuruAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepolarIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class DepolarIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikVergiNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo {
            get {
                return this.TcKimlikVergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikVergiNoField, value) != true)) {
                    this.TcKimlikVergiNoField = value;
                    this.RaisePropertyChanged("TcKimlikVergiNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepolarCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class DepolarCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.DepoDTO> DepolarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.DepoDTO> Depolar {
            get {
                return this.DepolarField;
            }
            set {
                if ((object.ReferenceEquals(this.DepolarField, value) != true)) {
                    this.DepolarField = value;
                    this.RaisePropertyChanged("Depolar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepoDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class DepoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BeldeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepoAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HalicimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlceIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BeldeId {
            get {
                return this.BeldeIdField;
            }
            set {
                if ((this.BeldeIdField.Equals(value) != true)) {
                    this.BeldeIdField = value;
                    this.RaisePropertyChanged("BeldeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepoAdi {
            get {
                return this.DepoAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.DepoAdiField, value) != true)) {
                    this.DepoAdiField = value;
                    this.RaisePropertyChanged("DepoAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Halicimi {
            get {
                return this.HalicimiField;
            }
            set {
                if ((this.HalicimiField.Equals(value) != true)) {
                    this.HalicimiField = value;
                    this.RaisePropertyChanged("Halicimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlId {
            get {
                return this.IlIdField;
            }
            set {
                if ((this.IlIdField.Equals(value) != true)) {
                    this.IlIdField = value;
                    this.RaisePropertyChanged("IlId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceId {
            get {
                return this.IlceIdField;
            }
            set {
                if ((this.IlceIdField.Equals(value) != true)) {
                    this.IlceIdField = value;
                    this.RaisePropertyChanged("IlceId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubelerIstek", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class SubelerIstek : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikVergiNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TcKimlikVergiNo {
            get {
                return this.TcKimlikVergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikVergiNoField, value) != true)) {
                    this.TcKimlikVergiNoField = value;
                    this.RaisePropertyChanged("TcKimlikVergiNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubelerCevap", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.ServiceContract")]
    [System.SerializableAttribute()]
    public partial class SubelerCevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<OmegaHKS.GenelServiceReference.SubeDTO> SubelerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((this.HataKoduField.Equals(value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.SubeDTO> Subeler {
            get {
                return this.SubelerField;
            }
            set {
                if ((object.ReferenceEquals(this.SubelerField, value) != true)) {
                    this.SubelerField = value;
                    this.RaisePropertyChanged("Subeler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubeDTO", Namespace="http://schemas.datacontract.org/2004/07/GTB.HKS.Genel.Model")]
    [System.SerializableAttribute()]
    public partial class SubeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BeldeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IlceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsyeriTuruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubeAdiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BeldeId {
            get {
                return this.BeldeIdField;
            }
            set {
                if ((this.BeldeIdField.Equals(value) != true)) {
                    this.BeldeIdField = value;
                    this.RaisePropertyChanged("BeldeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlId {
            get {
                return this.IlIdField;
            }
            set {
                if ((this.IlIdField.Equals(value) != true)) {
                    this.IlIdField = value;
                    this.RaisePropertyChanged("IlId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IlceId {
            get {
                return this.IlceIdField;
            }
            set {
                if ((this.IlceIdField.Equals(value) != true)) {
                    this.IlceIdField = value;
                    this.RaisePropertyChanged("IlceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsyeriTuru {
            get {
                return this.IsyeriTuruField;
            }
            set {
                if ((this.IsyeriTuruField.Equals(value) != true)) {
                    this.IsyeriTuruField = value;
                    this.RaisePropertyChanged("IsyeriTuru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubeAdi {
            get {
                return this.SubeAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SubeAdiField, value) != true)) {
                    this.SubeAdiField = value;
                    this.RaisePropertyChanged("SubeAdi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gtb.gov.tr//WebServices", ConfigurationName="GenelServiceReference.IGenelService")]
    public interface IGenelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIller", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIllerResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_IllerCevap GenelServisIller(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_IllerIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIlceler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIlcelerResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_IlcelerCevap GenelServisIlceler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_IlcelerIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisBeldeler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisBeldelerResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_BeldelerCevap GenelServisBeldeler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_BeldelerIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisUlkeler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisUlkelerResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_UlkelerCevap GenelServisUlkeler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_UlkelerIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisHalIciIsyeri", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisHalIciIsyeriResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_HalIciIsyeriCevap GenelServisHalIciIsyeri(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_HalIciIsyeriIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIsletmeTurleri", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisIsletmeTurleriRespons" +
            "e")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_IsletmeTurleriCevap GenelServisIsletmeTurleri(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_IsletmeTurleriIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisDepolar", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisDepolarResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_DepolarCevap GenelServisDepolar(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_DepolarIstek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisSubeler", ReplyAction="http://www.gtb.gov.tr//WebServices/IGenelService/GenelServisSubelerResponse")]
        OmegaHKS.GenelServiceReference.BaseResponseMessageOf_SubelerCevap GenelServisSubeler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_SubelerIstek request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_IllerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_IllerIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.IllerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_IllerIstek() {
        }
        
        public BaseRequestMessageOf_IllerIstek(OmegaHKS.GenelServiceReference.IllerIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_IllerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_IllerCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.IllerCevap Sonuc;
        
        public BaseResponseMessageOf_IllerCevap() {
        }
        
        public BaseResponseMessageOf_IllerCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.IllerCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_IlcelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_IlcelerIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.IlcelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_IlcelerIstek() {
        }
        
        public BaseRequestMessageOf_IlcelerIstek(OmegaHKS.GenelServiceReference.IlcelerIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_IlcelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_IlcelerCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.IlcelerCevap Sonuc;
        
        public BaseResponseMessageOf_IlcelerCevap() {
        }
        
        public BaseResponseMessageOf_IlcelerCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.IlcelerCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_BeldelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_BeldelerIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.BeldelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_BeldelerIstek() {
        }
        
        public BaseRequestMessageOf_BeldelerIstek(OmegaHKS.GenelServiceReference.BeldelerIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_BeldelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_BeldelerCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.BeldelerCevap Sonuc;
        
        public BaseResponseMessageOf_BeldelerCevap() {
        }
        
        public BaseResponseMessageOf_BeldelerCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.BeldelerCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_UlkelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_UlkelerIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.UlkelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_UlkelerIstek() {
        }
        
        public BaseRequestMessageOf_UlkelerIstek(OmegaHKS.GenelServiceReference.UlkelerIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_UlkelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_UlkelerCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.UlkelerCevap Sonuc;
        
        public BaseResponseMessageOf_UlkelerCevap() {
        }
        
        public BaseResponseMessageOf_UlkelerCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.UlkelerCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_HalIciIsyeriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_HalIciIsyeriIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.HalIciIsyeriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_HalIciIsyeriIstek() {
        }
        
        public BaseRequestMessageOf_HalIciIsyeriIstek(OmegaHKS.GenelServiceReference.HalIciIsyeriIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_HalIciIsyeriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_HalIciIsyeriCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.HalIciIsyeriCevap Sonuc;
        
        public BaseResponseMessageOf_HalIciIsyeriCevap() {
        }
        
        public BaseResponseMessageOf_HalIciIsyeriCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.HalIciIsyeriCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_IsletmeTurleriIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_IsletmeTurleriIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.IsletmeTurleriIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_IsletmeTurleriIstek() {
        }
        
        public BaseRequestMessageOf_IsletmeTurleriIstek(OmegaHKS.GenelServiceReference.IsletmeTurleriIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_IsletmeTurleriCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_IsletmeTurleriCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.IsletmeTurleriCevap Sonuc;
        
        public BaseResponseMessageOf_IsletmeTurleriCevap() {
        }
        
        public BaseResponseMessageOf_IsletmeTurleriCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.IsletmeTurleriCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_DepolarIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_DepolarIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.DepolarIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_DepolarIstek() {
        }
        
        public BaseRequestMessageOf_DepolarIstek(OmegaHKS.GenelServiceReference.DepolarIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_DepolarCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_DepolarCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.DepolarCevap Sonuc;
        
        public BaseResponseMessageOf_DepolarCevap() {
        }
        
        public BaseResponseMessageOf_DepolarCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.DepolarCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseRequestMessageOf_SubelerIstek", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseRequestMessageOf_SubelerIstek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public OmegaHKS.GenelServiceReference.SubelerIstek Istek;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public string ServicePassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=3)]
        public string UserName;
        
        public BaseRequestMessageOf_SubelerIstek() {
        }
        
        public BaseRequestMessageOf_SubelerIstek(OmegaHKS.GenelServiceReference.SubelerIstek Istek, string Password, string ServicePassword, string UserName) {
            this.Istek = Istek;
            this.Password = Password;
            this.ServicePassword = ServicePassword;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BaseResponseMessageOf_SubelerCevap", WrapperNamespace="http://www.gtb.gov.tr//WebServices", IsWrapped=true)]
    public partial class BaseResponseMessageOf_SubelerCevap {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=0)]
        public System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=1)]
        public string IslemKodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.gtb.gov.tr//WebServices", Order=2)]
        public OmegaHKS.GenelServiceReference.SubelerCevap Sonuc;
        
        public BaseResponseMessageOf_SubelerCevap() {
        }
        
        public BaseResponseMessageOf_SubelerCevap(System.Collections.Generic.List<OmegaHKS.GenelServiceReference.ErrorModel> HataKodlari, string IslemKodu, OmegaHKS.GenelServiceReference.SubelerCevap Sonuc) {
            this.HataKodlari = HataKodlari;
            this.IslemKodu = IslemKodu;
            this.Sonuc = Sonuc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenelServiceChannel : OmegaHKS.GenelServiceReference.IGenelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenelServiceClient : System.ServiceModel.ClientBase<OmegaHKS.GenelServiceReference.IGenelService>, OmegaHKS.GenelServiceReference.IGenelService {
        
        public GenelServiceClient() {
        }
        
        public GenelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_IllerCevap GenelServisIller(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_IllerIstek request) {
            return base.Channel.GenelServisIller(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_IlcelerCevap GenelServisIlceler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_IlcelerIstek request) {
            return base.Channel.GenelServisIlceler(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_BeldelerCevap GenelServisBeldeler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_BeldelerIstek request) {
            return base.Channel.GenelServisBeldeler(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_UlkelerCevap GenelServisUlkeler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_UlkelerIstek request) {
            return base.Channel.GenelServisUlkeler(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_HalIciIsyeriCevap GenelServisHalIciIsyeri(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_HalIciIsyeriIstek request) {
            return base.Channel.GenelServisHalIciIsyeri(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_IsletmeTurleriCevap GenelServisIsletmeTurleri(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_IsletmeTurleriIstek request) {
            return base.Channel.GenelServisIsletmeTurleri(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_DepolarCevap GenelServisDepolar(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_DepolarIstek request) {
            return base.Channel.GenelServisDepolar(request);
        }
        
        public OmegaHKS.GenelServiceReference.BaseResponseMessageOf_SubelerCevap GenelServisSubeler(OmegaHKS.GenelServiceReference.BaseRequestMessageOf_SubelerIstek request) {
            return base.Channel.GenelServisSubeler(request);
        }
    }
}
